[package]
name = "gzip-size-cli"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "gzip-size"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.56"
atty = "0.2.14"
clap = { version = "3.1.8", features = ["derive"] }
flate2 = "1.0.22"
humansize = "1.1.1"

[profile.release]
lto = "fat"
