[package]
name = "gzip-size-cli"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "gzip-size"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.56"
atty = "0.2.14"
clap = { version = "4.0.0", features = ["derive"] }
flate2 = "1.0.22"
humansize = "2.0.0"

[profile.release]
lto = "fat"
